### ISSUE TITLE
Reload after submit breaks the page

### ISSUE THREAD

**Issue by Khrysller** [timabell/jquery-stickytabs#1]
I think this is breaking the page in the following scenario:
- page1 is a form, after submit goes to page 2
- page 2 has some results from the form.
- If I navigate in tabs, it will add the tab #Name in the url
- If I refresh, I lost the form data, and page comes without data.

Gonna do a test in the office in the morning.

**Comment by timabell** [comment]
hi, this fork is only for the nuget packaging, and lags behind the official version
- if it's an issue with upstream that hasn't been fixed there please report it there https://github.com/aidanlister/jquery-stickytabs/issues
- if it's been fixed and released upstream and just needs packaging for nuget then mention that here and I'll endeavour to release a new package

thanks
